@api = http://localhost:3000/api

### get All users
GET {{api}}/get

### Add user
POST {{api}}/post
Content-Type: application/json

{
  "username": "Njm Jr",
  "password": "password",
  "email": "njm@outlook.com"

}

### get user by Id
GET {{api}}/get/<id>

### update users By Id
PUT {{api}}/put/<id>
Content-Type: application/json

{
  "username": "Jr Njm",
  "password": "password",
 "email": "najmejarray@gmail.com"
 }

### delete users by Id
DELETE {{api}}/del/<Id>